disabled_rules:
  - function_body_length
  - identifier_name
  - trailing_comma
excluded:
  - .build
  - Carthage
  - Tests/*/XCTestManifests.swift
nesting:
  type_level: 2
trailing_comma:
  mandatory_comma: true
