language: objective-c
osx_image: xcode8.3
install:
  - gem install xcpretty
  - rake setup
matrix:
  include:
    - env: ACTION=test:osx
    - env: ACTION=test:ios
    - env: ACTION=test:tvos
    - env: ACTION=build:carthage:ios
    - env: ACTION=build:carthage:macos
    - env: ACTION=build:carthage:tvos
    - env: ACTION=build:carthage:watchos
    - env: ACTION=build:pod
    - env: ACTION=build:package
    - env: ACTION=test:package
    - env: ACTION=test:package
      os: linux
      language: generic
      sudo: required
      dist: trusty
      install:
        - eval "$(cat bin/setup-swiftenv.bash)"
        - bin/swiftenv-install
    - env: ACTION=test:package
      os: linux
      language: generic
      sudo: required
      dist: trusty
      install:
        - eval "$(cat bin/setup-swiftenv.bash)"
        - env SWIFT_VERSION=$(bin/latest-snapshot '^4.0') bin/swiftenv-install
  fast_finish: true
script: rake "$ACTION"
